name = "FastLink"
uuid = "11f39cfd-5548-489f-be9a-f4ad0ff6eadc"
authors = ["Jack R. Williams <contact@jackryanwilliams.com>"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
